### PR TITLE
fAIr production link fixes

### PR DESCRIPTION
**Pull request by omranlm**
Changes: 
updating fAIr link to production env in the hotosm website in 3 locations:
1- fAIr main page
2- Tech suite page
3- Open data solutions page

### CODE REVIEW

**Comment by omranlm** [comment]
@omranlm  @dakotabenjamin for your kind review

**Comment by omranlm** [comment]
@dakotabenjamin / @kshitijrajsharma how can I make sure this is deployed? the changes are not reflected in the website!

**Comment by dakotabenjamin** [comment]
@omranlm @Claurt07 recently changed how the tools&data page works, and it looks like the pages are actually in a different location. Claudio can you help here? Omran wishes to update the URL for fAIr to link out properly.

**Comment by dakotabenjamin** [comment]
Try updating these: https://github.com/search?q=repo%3Ahotosm%2Fhotosm-website%20fair-dev&type=code

**Pull request merged**
