### PR TITLE
Repeople

### LINKED ISSUE #254: Organize people listing within repo/Siteleaf
We just have a people folder. It might be helpful to have folders to organize staff, voting members, board.

### PR DESCRIPTION
**Pull request by arunasank**
Fixes https://github.com/hotosm/hotosm-website/issues/254 when done.

## Two issues remain
I am new to Jekyll, and trying to fix the following. Let me know if any of you have thoughts
@hotosm/tech-staff 

* Currently, I see that the staff page looks ok, however the `_layouts/roster.html` is not even called when the `Voting Members` and `Board Members` link is selected. Investigating what I need to change to fix this.
<details>
screen shot 2019-01-04 at 3 44 06 pm
screen shot 2019-01-04 at 3 44 16 pm
</details>
<br/>

* Secondly, the people pages for individuals is messed up for everyone except voting members. Investigating why, and what fixes need to happen here.
<details>
screen shot 2019-01-04 at 3 44 42 pm
</details>

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
@arunasank - when there is a collection/folder present with the same name as markdown file, the collection seems to get the precedence. So in our case markdown file is not invoked for `voting-members/` path. Markdown file has the reference to the `roster`. So instead of getting the `roster` layout just the folder contents are displayed.  I tried moving this as a subfolder under `people` and the markdown gets invoked.  People list is empty because we're not handling this in the `roster` file yet.

image

**Comment by arunasank** [comment]
@ramyaragupathy Thanks for investigating! This clarifies a lot of things to me. 🙇‍♀️ I will make the fixes. 

@ramyaragupathy and others on @hotosm/tech are there resources you like using for Jekyll advanced usage?

**Comment by smit1678** [comment]
> @ramyaragupathy and others on @hotosm/tech are there resources you like using for Jekyll advanced usage?

@arunasank For the Liquid templating, this is a good resource: https://shopify.github.io/liquid/. For overall Jekyll layouts, etc: https://learn.cloudcannon.com/

**Comment by ramyaragupathy** [comment]
Usually refer to:
- [Jekyll documentation](https://jekyllrb.com/docs/)
- [Jekyll Forum](http://talk.jekyllrb.com/)

**Comment by arunasank** [comment]
We are currently trying to figure out if we can use sub-collections on Jekyll. If yes, this would be the preferred approach.

If we cannot figure out sub-collections, we can decide between
* Renaming all the pages to be `staff-*`, `vote-*` or `board-*` or `staff-board-*` etc, and keeping them all aggregated like they are right now. If we go down this route we would have to modify the permalinks to the pages per conversation with @smit1678 and @ramyaragupathy. 
* Grouping files in separate collections, as done on this PR, but if we go down this path, we need to figure out ways to de-duplicate files about members who belong to two different groups. For example, someone who is a voting member and a staff.

**Comment by arunasank** [comment]
Thanks @smit1678 for simplifying this entire fix, and @ramyaragupathy for helping debug. 🙏 

I have moved the files to their sub-collections, after @smit1678's fix to `config.yml`.

**Comment by arunasank** [comment]
I built the website locally, and things look good! 

screen shot 2019-01-14 at 4 35 38 pm
screen shot 2019-01-14 at 4 35 52 pm
screen shot 2019-01-14 at 4 36 02 pm

## Amelia Hunt - archived, is not clickable from a blog post

screen shot 2019-01-14 at 4 39 21 pm

**Comment by smit1678** [comment]
Nice work @arunasank! 👏 👍 🎉 

Did a quick review and everything looks good.

**Review by smit1678 — APPROVED** [review]

**Pull request merged**
