### PR TITLE
Place the country title at bottom of map

### PR DESCRIPTION
**Pull request by uwaiszaki**
Fix for the issue #359 
After Changes ->
hostosmwebsiteissue359

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
One minor improvement @uwaiszaki - title box should be aligned with the HOT logo at the top. Attaching a screenshot from `Our work` page for reference.

image



image

**Comment by uwaiszaki** [comment]
Thanks for your response @ramyaragupathy, I have updated the pr to follow the logo alignment.

**Comment by ramyaragupathy** [comment]
Aligned well- thanks for the fix @uwaiszaki! Good to merge @smit1678

**Review by ramyaragupathy — APPROVED** [review]

**Comment by smit1678** [comment]
Thanks for the work @uwaiszaki. One quick mobile fix and then I think this is good to go: 

Humanitarian OpenStreetMap Team | Tanzania 2019-03-16 11-42-01

**Comment by uwaiszaki** [comment]
@smit1678 @ramyaragupathy Now it handles mobile view for country title. 
hotosmwebsiteissue359(2)

**Review by ramyaragupathy — COMMENTED** [review]
Works as expected on mobile platforms

**Pull request merged**
