### PR TITLE
Create 2018-06-14-hot-2018-annual-meeting-and-election-results.markdown

### PR DESCRIPTION
**Pull request by IknowJoseph**
Please let me know of issues with this file. I'm not sure if the date section is correct, for example?

### CODE REVIEW

**Comment by brendangatens** [comment]
I think you'll need to get rid of those `+` characters that may have been copied from the previous PR. A job for me though, might be to update the design of the homepage news module for when the most recent post has no image. Ends up looking like this:

screenshot 2018-06-14 10 34 13

**Comment by IknowJoseph** [comment]
@brendangatens Thanks for the spot, I've removed those now.

Images is a question I had: Should I put one in this post? I don't have a hugely relevant example, but perhaps we could use some sort of HOT Stock Photo?

**Comment by brendangatens** [comment]
My opinion is that if there isn't a relevant image to use, then we shouldn't need to use an image. If there is a stock photo that clearly explains the concept of the post, then it shouldn't be a problem to go with that. I don't think we should force it, however. With that, I think it's important that the design of all the news modules can accommodate for the lack of an image. It's just the one on the homepage that fails to do that. I'll create an issue.

**Comment by smit1678** [comment]
Agreed that if there isn't an image to use, let's not use one. @brendangatens shall we hold on merging this until we figure out how to handle it?

**Comment by smit1678** [comment]
@IknowJoseph Until we get a good solution for no pictures, what about just using a screenshot of the board page? Or one from a previous board meeting? 

I've messaged Trudy to see if we can get a picture for her profile. 

humanitarian openstreetmap team board 2018-06-17 10-00-01

**Comment by IknowJoseph** [comment]
@smit1678 Thanks, could you check my latest edit?

**Comment by smit1678** [comment]
@IknowJoseph 👍  going to merge and then update the screenshot with an updated board page now that Trudy added her photo.

**Pull request merged**
