### PR TITLE
[wip] Docs and Guidelines

### PR DESCRIPTION
**Pull request by arunasank**
Fixes https://github.com/hotosm/hotosm-website/issues/398 and https://github.com/hotosm/hotosm-website/issues/386 when done. 

## Current Look

screen shot 2019-01-18 at 6 47 36 pm

## Things done
* [x] Create markdown pages for the wiki content, after organising this content into sub-sections
* [x] Placement for the docs page - this is going to be part of the footer
* [x] Redesign the footer to be more balanced
* [x] Bring more visibility to the media toolkit and to the organizational bylaws and articles of incorporation

## TODO
* [x] Design a layout for the docs page, and make decisions around including the markdown content here.
* [x] Include Github in the list of social media links
* [x] Remove Media Toolkit from the contact page, or modify its presence there, to reflect the new changes.

cc/ @hotosm/tech

### CODE REVIEW

**Comment by arunasank** [comment]
The GitHub SVG logo is from https://github.com/GoogleChrome/browser-bug-search/blob/master/img/octocat.svg. @willemarcel found this by looking for `GitHub-Mark-Light` (The name is from the GitHub resources for the logo). Would be nice to get a sense for how we generally do this for other icons.

**Comment by arunasank** [comment]
### Docs landing page
screen shot 2019-01-25 at 6 27 03 pm

-----------------------

### An example docs page
screen shot 2019-01-25 at 6 27 20 pm

----------------------------

Thanks for pairing with me to get the kinks sorted in these pages @smit1678.

* The individual docs pages now follow the layout of the `page.html` layout file.
* The docs landing page follows the layout of the `groups.html` layout file.
* We have a link to the #hotosm-website slack channel on each docs page.

@smit1678 @ramyaragupathy can one of you review this for me?

Some things I am specifically concerned about:
* The sizes of the colour tiles in the `colours-fonts-logo` page.

**Comment by ramyaragupathy** [comment]
Awesome 🎉 - added in style changes that worked for the logo file @arunasank. Other items that I feel could be modified:

### Adjusting logos in the footer with the text height
image
 
### Adding slack links in the sidebar text

image

**Comment by arunasank** [comment]
Thanks for reviewing @ramyaragupathy. ♥️ 

> Adding slack links in the sidebar text

The support button leads to the slack channel. Can you clarify what you mean here? 

@ramyaragupathy

**Comment by ramyaragupathy** [comment]
Didn't check the support button link to Slack @arunasank. That should work great.

**Comment by arunasank** [comment]
I'll reword that button text @ramyaragupathy. Thanks for the tip!

**Comment by smit1678** [comment]
@arunasank Awesome work. I made a couple changes to rearrange the post order, renamed some titles, and added some text.

**Comment by smit1678** [comment]
👍 Last review looks good. Made a quick adjustment to the footer to separate the Bylaws and Articles of Incorporation to be two lines which looks better. And then moved the social icons over to give more space to the footer to keep and keep in line with the original design.

**Pull request merged**
