### PR TITLE
Fix donation page rendering issues

### PR DESCRIPTION
**Pull request by eternaltyro**
Fixes issue where donate form is not rendered in https://www.hotosm.org/donate/

Changes: 
Add new script-src source for cdn.donately.com

### CODE REVIEW

**Review by willemarcel — CHANGES_REQUESTED** [review]
It's not rendering to me 
```
Content Security Policy: The page’s settings blocked the loading of a resource at http://cdn.trackjs.com/releases/current/tracker.js (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://b.donately.com/ (“connect-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at http://cdn.donately.com/963UiWkR/init.js?_=1612864167211 (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://matomo.hotosm.org/piwik.php?action_name=Humanitarian%20OpenStreetMap%20Team%20%7C%20Support%20HOT%27s%20work%3A%20Donate%20today!&idsite=1&rec=1&r=403829&h=6&m=49&s=29&url=http%3A%2F%2Flocalhost%3A4000%2Fdonate%2F&_id=7a32ce59e5804de9&_idts=1591897569&_idvc=26&_idn=0&_refts=1612864126&_viewts=1612452699&_ref=http%3A%2F%2F127.0.0.1%3A4000%2Fpeople%2F&send_image=1&cookie=1&res=1920x1080&gt_ms=0&pv_id=d6Yjqy&consent=1 (“img-src”).
```

**Comment by eternaltyro** [comment]
> It's not rendering to me
> 
> ```
> Content Security Policy: The page’s settings blocked the loading of a resource at http://cdn.trackjs.com/releases/current/tracker.js (“script-src”).
> Content Security Policy: The page’s settings blocked the loading of a resource at https://b.donately.com/ (“connect-src”).
> Content Security Policy: The page’s settings blocked the loading of a resource at http://cdn.donately.com/963UiWkR/init.js?_=1612864167211 (“script-src”).
> Content Security Policy: The page’s settings blocked the loading of a resource at https://matomo.hotosm.org/piwik.php?action_name=Humanitarian%20OpenStreetMap%20Team%20%7C%20Support%20HOT%27s%20work%3A%20Donate%20today!&idsite=1&rec=1&r=403829&h=6&m=49&s=29&url=http%3A%2F%2Flocalhost%3A4000%2Fdonate%2F&_id=7a32ce59e5804de9&_idts=1591897569&_idvc=26&_idn=0&_refts=1612864126&_viewts=1612452699&_ref=http%3A%2F%2F127.0.0.1%3A4000%2Fpeople%2F&send_image=1&cookie=1&res=1920x1080&gt_ms=0&pv_id=d6Yjqy&consent=1 (“img-src”).
> ```

I updated the code to include trackjs and matomo. I have no idea why the cdn.donately.com part doesn't work. Can you check now? @willemarcel

**Comment by willemarcel** [comment]
@eternaltyro I tried on Chromium and Firefox and still have the error on trackjs and donately and the form doesn't render.

**Comment by eternaltyro** [comment]
I have made yet more changes based on console errors that @willemarcel experienced.

**Comment by willemarcel** [comment]
@eternaltyro Now it renders the form!
I noticed the donately form uses captcha, probably it will need to load an image after posting the form. How we assure it will load correctly?

I don't think keeping CSP headers is maintainable. If donately changes an url or someone embeds some other platform content or uses an image hosted on another website, it will also fail. What is your plan about that?

**Comment by dakotabenjamin** [comment]
Is there a sort of linter or test we can scan code and PRs for external links?

**Comment by eternaltyro** [comment]
@willemarcel every time a change is made, if there's a new integration, errors will show up in console during testing if the CSP is not updated. I don't think there will be much difficulty maintaining the list since all browsers flag CSP errors reliably even in local testing scopes.

**Comment by eternaltyro** [comment]
> Is there a sort of linter or test we can scan code and PRs for external links?

@dakotabenjamin not that I know of. We need to somehow load every page of the website in order to trigger CSP violations to see if all cases are covered.

**Comment by willemarcel** [comment]
> @willemarcel every time a change is made, if there's a new integration, errors will show up in console during testing if the CSP is not updated. I don't think there will be much difficulty maintaining the list since all browsers flag CSP errors reliably even in local testing scopes.

@eternaltyro most changes on the website are done by siteleaf, not by pull requests. If you and @dakotabenjamin want to take the responsibility to assure all the website works always correctly, I'm ok with keeping the CSP headers. But I don't want that responsibility.

**Pull request closed without merging**
