### PR TITLE
add loading map indicator to our-work page

### PR DESCRIPTION
**Pull request by willemarcel**
I added a loading map indicator to the our-work page. I can apply the same behaviour to other page maps if it's approved, @smit1678 @ramyaragupathy

### CODE REVIEW

**Comment by smit1678** [comment]
👍 from me, I think that's helpful. Should we use the same spinner as we do on the stats for consistency?

**Comment by ramyaragupathy** [comment]
This behavior is super useful for the end user! I was just checking the changes on this branch and replicated the behavior for impact-area map as well. Noticed your comment after checking-in @willemarcel, feel free to revert if needed.

**Comment by willemarcel** [comment]
@smit1678 I changed the spinner to use the same as the stats. Is it ok if it's red instead of gray?

Thanks, @ramyaragupathy !

**Comment by smit1678** [comment]
Dig it. 👍

**Pull request merged**
