### PR TITLE
Fetch data from stats-collector output

### PR DESCRIPTION
**Pull request by ramyaragupathy**
Related issue: https://github.com/hotosm/hotosm-website/issues/320
 
Home page a& country page now pulls in numbers from `aggregatedStats.json`. Lag is < 3 seconds and doesn't quite stand out like how it was earlier

**Home page**
homepage

**Country page**
countrypage

**Tooltip text**
image

### Items to discuss
- Certain countries like Venezuela doesn't have any project listed on TM, but still highlighted on the map. In this scenario, osm-stats remains as fallback
- There are countries like `Gambia`, `Trinidad & Tobago` where TM has projects listed, but not highlighted on `our-work` map.
- Github integration vs direct pull from S3
- Access token as env variable in lambda

## To do
- [x] update tooltip text
- [x] update branch name in `stats-collector`
- [x] switch to TM production link
- [x] adjust last active difference 
- [x] upload zip to lambda

cc @smit1678

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
Noticing that the lambda has checked in files only 3 times on June 19 & June 20. 6PM (18:00 GMT) check-in is missing. However I could see the lambda scheduled to run for 4 times a day, including 18:00 GMT

image

**Comment by ramyaragupathy** [comment]
So events are scheduled as expected and also triggered (confirmed this from logs). However the log does not have the success message for github check-in during some runs. Guessing that the data fetch from endpoints are failing and the lambda function has no event listener. Adding error logs to the lambda. https://github.com/hotosm/stats-collector/issues/2

**Comment by ramyaragupathy** [comment]
Added error messages/logs to the lambda for each endpoint. If there's any failure scenario, github check-in fails, fallback would be the files from last successful run.

**Comment by smit1678** [comment]
@ramyaragupathy Looks good 👍 Merging and then we can move on to https://github.com/hotosm/hotosm-website/issues/327 to put back in the all OSM stats for the country pages.

**Comment by ramyaragupathy** [comment]
Thanks @smit1678, updating items in `stats-collector`

**Pull request merged**
