### PR TITLE
Country level stats

### PR DESCRIPTION
**Pull request by ramyaragupathy**
Referring to issue #191 

image

Buildings mapped = buildings added + buildings modified
Roads mapped = roads added + roads modified

For now, placing the data immediately below the map to give an overview of the country. 

### Code Additions/Modifications

Used the existing code for:
- Information `div`
- Data formatting

Additions:
- `missingMapsCode` variable for country code from liquid variable. Country codes length: 3 chars and they match with the [Missing Maps codes](https://osm-stats-production-api.azurewebsites.net/countries)
- `countries-stats.js` to gather stats from Missing maps API. Here's a sample data returned:

```json
{"all_edits":22071532,"road_count_add":1379752,"road_count_mod":2178512,"building_count_add":15328931,"building_count_mod":2026341,"waterway_count_add":909654,"poi_count_add":248342,"road_km_add":664027.033173935,"road_km_mod":2157121.51713229,"contributors":15388}
```

### Flags 🔴 

- Each API call takes more close to 30s. End user experiences a visible lag in data presentation.
- [Indonesia query](https://osm-stats-production-api.azurewebsites.net/countries/idn) failure with the following error:
`GET https://osm-stats-production-api.azurewebsites.net/countries/IDN 502 (Bad Gateway)
(index):1 Failed to load https://osm-stats-production-api.azurewebsites.net/countries/IDN: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access. The response had HTTP status code 502.`

### Questions ❓ 

@smit1678 -  

- API query is called during `document.ready()`. Could you please suggest a better place to position data fetch for a smooth experience?
- Any pointers to investigate on Indonesia query failure? Other country queries take time, but gets through with a positive response.

### CODE REVIEW

**Comment by smit1678** [comment]
> API query is called during document.ready(). Could you please suggest a better place to position data fetch for a smooth experience?

Tagging @willemarcel @dakotabenjamin as they might have a recommendation 

> Any pointers to investigate on Indonesia query failure? Other country queries take time, but gets through with a positive response.

Odd. It looks like the 3 letter code is correct: https://osm-stats-production-api.azurewebsites.net/countries.

**Comment by smit1678** [comment]
@ramyaragupathy Looks like buildings numbers are being concatenated

fireshot capture 9 - humanitarian openstreetmap team _ - http___localhost_4000_where-we-work_uganda_

**Comment by ramyaragupathy** [comment]
Thanks for the catch @smit1678! Rearranged the string formatting after building count sum up.

image

**Comment by smit1678** [comment]
Great, good from my end. :+1:

**Comment by ramyaragupathy** [comment]
> - API query is called during `document.ready()`. Could you please suggest a better place to position data fetch for a smooth experience?

Per chat w/ @smit1678 digging into loading issues: https://github.com/hotosm/hotosm-website/issues/222

**Comment by ramyaragupathy** [comment]
So there's a loader in place while the numbers are fetched from Missing Maps.
loader

However I need some clarity on the css flow within the project so that I could align the loader much better. For now I'm doing the local testing by updating style in `main.scss`.  @smit1678 - Would like to chat a little bit more about css structure before heading further.

**Comment by smit1678** [comment]
@ramyaragupathy Awesome :+1: . The correct place for styles is within the `_sass` folder: https://github.com/hotosm/hotosm-website/blob/gh-pages/_sass/base.scss

**Comment by ramyaragupathy** [comment]
Thanks, just pushed it! 
- [x] Align the loading icon to the center

**Comment by ramyaragupathy** [comment]
- Center aligned the loading animation for country stats.

loader

- Integrated loading animation for home page: In the home page, data is fetched from two different APIs (TM for mappers count & Missing maps for edits/feature count). In this case, just hiding/showing the entire `loader` class will not help. Instead assigned an `id` for each load element in the stats section & then used the jquery id selector to hide/show individual `loader` elements.
loader


@smit1678 - Anything else to improvise here?

**Comment by smit1678** [comment]
@ramyaragupathy Looks great, works great. :+1: @dakotabenjamin Can you approve and merge?

**Pull request merged**
