### PR TITLE
adjust impact area layout to match our work layout

### PR DESCRIPTION
**Pull request by smit1678**
@brendangatens @willemarcel Not sure if this is the vision but here is a fix to the impact areas page so the map works similarly to the our work page. 

@brendangatens This doesn't factor for the updated style that you made for the impact area links on the our work page. Is that something you want to see here?

fireshot capture 1 - humanitarian openst_ - http___localhost_4000_impact-areas_water-and-sanitation_

### CODE REVIEW

**Comment by brendangatens** [comment]
@smit1678 yeah, I'd like to display the map at that size but with it only highlighting countries that have projects from the chosen impact area.

I don't think we ever planned on having the list of impact areas on top of the map, as we do on the _Our Work_ map. We might want to include the `impact-areas.html` include at the bottom of these pages though.

**Comment by smit1678** [comment]
> yeah, I'd like to display the map at that size but with it only highlighting countries that have projects from the chosen impact area.

Ok, so that will require us to generate that information into the json file for the map. Should we not include the map then on the impact areas for now until we have that ready?

**Comment by smit1678** [comment]
@brendangatens Or should we just go with keeping all projects in the map view for now and make sure that is clear. I think if we filter by impact areas at the moment, the number of projects is going to be pretty low.

**Comment by willemarcel** [comment]
I think the ideal would be to filter the countries that have projects on the current impact area. If it's not possible, we should highlight only countries with projects on the map.

**Comment by brendangatens** [comment]
I don't really have a preference if we're looking at a temporary solution of either getting rid of the map, or just including all countries. Whichever is quickest if we're trying to get a PR up. Just need to make sure that the header isn't collapsed if we go with no map.

When we do implement a filtered map, I think that a map highlighting a low number of countries still tells a clearer story than a map showing all HOT countries. Maybe we zoom into those areas on map load, as @willemarcel has done on the country and profile maps.

**Comment by willemarcel** [comment]
@smit1678 I have changed the map height and modified it to highlight only the countries with projects.

**Pull request merged**
