### PR TITLE
Fix news section in country pages#483

### LINKED ISSUE #483: Fix news section in where we work page
@ramyaragupathy  @smit1678  better handling of date and author field in where we work country pages are required .i would like to fix it.
Screenshot from 2019-03-20 23-53-29
Screenshot from 2019-03-21 10-26-35

### PR DESCRIPTION
**Pull request by Muskan284**
@ramyaragupathy  kindly review .
also can u suggest other issues to work upon.
fixes #483 
Screenshot from 2019-03-21 12-20-37

### CODE REVIEW

**Comment by uwaiszaki** [comment]
@ramyaragupathy I pr similar to this was merged 67d8d595d411430f963cdbf1b88dc36ace541d40.
But it's not showing the code in the changed code. Please look into this.

**Comment by Muskan284** [comment]
@uwaiszaki  there was a similar issue that u solved and that pr has been merged but that solved the problem only for project pages.This issue is for country pages

**Comment by uwaiszaki** [comment]
@ramyaragupathy 67d8d595d411430f963cdbf1b88dc36ace541d40 was merged for #421 which changed author.html for project page but this is not showing those changes in it.

**Comment by Muskan284** [comment]
@ramyaragupathy  kindly review this pr.

**Review by ramyaragupathy — CHANGES_REQUESTED** [review]
@Muskan284 - Thanks for spotting and working on this issue.

As highlighted in your issue there are two `-` separators in the news section. Your fix should retain just one separator. However I don't see any separators appearing now between author name and Date.

image

**Comment by ramyaragupathy** [comment]
Stale - will fix this in another PR

**Pull request closed without merging**
