### PR TITLE
Jekyll Update 3.5.2 => 3.8.5

### PR DESCRIPTION
**Pull request by arunasank**
Fixes https://github.com/hotosm/hotosm-website/issues/379

## What I did
```
$ rm Gemfile.lock
$ bundle update jekyll
$ bundle install # This generated a new Gemfile.lock
```

I also tested this, and the website builds and looks fine!

cc/ @hotosm/tech-staff

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
@arunasank - dependency still seem to list `3.5.2` https://github.com/hotosm/hotosm-website/blob/7cbe0bc2f13417bf98fc30b2ee805b1fa9a0bd39/Gemfile.lock#L63

**Comment by ramyaragupathy** [comment]
Looks like you'll have to update the version locked for bundle here l https://github.com/hotosm/hotosm-website/blob/gh-pages/Gemfile#L11 and then do the bundle update.

**Comment by arunasank** [comment]
Thanks for the review @ramyaragupathy! I've updated the Gemfile and the dependencies after your comment.

**Review by smit1678 — APPROVED** [review]
Tested and works. 👍

**Pull request merged**
