### PR TITLE
Enabling impact filters

### PR DESCRIPTION
**Pull request by ramyaragupathy**
Related to https://github.com/hotosm/hotosm-website/issues/231

As a first step, fetching the impact areas from across projects for each country. This could be implemented in `countries.json`. However having the liquid template as a separate file `impact-filter.json` for now.  

Each country object looks like 👇 

```json
"botswana": {
		"continent": "AF",
		"hot_program": true,
		"community_program": false,
		"member": false,
		"impact": " Disaster Risk Reduction,Public Health , "
	}
```
`impact` is a new property added for enabling filtering on map.

**To do**
- [x] Separate keys for each impact area
- [x] Use impact area keys to filter out countries

cc @smit1678

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
Updated the country object to generate a key for each impact area:

```json
"uganda": {
		"continent": "AF",
		"hot_program": true,
		"community_program": false,
		"Poverty Elimination": true,
		"Refugee Response": true,
		"member": true
	}
```
Also countries are now filtered on the map based on the impact page.

impact

I'd like to relook at the code and restructure it a bit if necessary. Spending an hour tomorrow my AM and then ping you for review @smit1678

**Comment by ramyaragupathy** [comment]
- Moved the impact data aggregation to `countries.json`
- removed `impact-filter.json`
- updated existing code to gather countries based on page title

@smit1678 - This is good for your review

**Comment by smit1678** [comment]
@ramyaragupathy Awesome, this looks and works great. Can we add the legend in the top right to keep consistency? Probably can drop members from the legend since we aren't showing those countries. 

humanitarian openstreetmap team our work 2018-05-31 10-53-49

**Comment by ramyaragupathy** [comment]
Yes, adding a legend gives a consistent look. Just updated the file.

image

**Comment by smit1678** [comment]
@ramyaragupathy Nice work, looks great. Merging...

**Pull request merged**
