### PR TITLE
Add Transition

### LINKED ISSUE #524: Add underline transition in nav-bar
The on-hover underlines come without any transitions and give an average user experience.
@ramyaragupathy I am working on adding this feature.
Screenshot from 2019-04-05 13-43-07

### PR DESCRIPTION
**Pull request by bismitaguha**
Fixes #524 . @ramyaragupathy Please review this PR.

### CODE REVIEW

**Review by ramyaragupathy — COMMENTED** [review]
Can you give me a gif/screenshots of the changes you have made? I am unable to spot any noticeable difference.
 
@codefab99 - Would like to hear more about your thoughts on design ideas for the nav bar.

**Comment by bismitaguha** [comment]
@ramyaragupathy More modification can be done by using 'text-decoration: underline' rather than 'border-bottom'. I feel that this change should be implemented throughout the site. Then considerable changes can be seen in the transitions added. That would be a major change in css throughout lots of classes and ids. So if you approve this as a new feature implementation, I would proceed towards working towards it.

**Comment by ramyaragupathy** [comment]
@codefab99 - can you please make quick mock ups or screenshots of the transitions you're thinking? It will be easier for me to follow your thinking here and then decide next course of action

**Comment by bismitaguha** [comment]
@ramyaragupathy I have integrated some changes into the nav. The transitions are being implemented. Please provide your suggestions on these changes :smiley:
transition

**Comment by ramyaragupathy** [comment]
Involves more design discussion, let's revisit based on inputs from user interviews.

**Pull request closed without merging**
