### PR TITLE
Migrate Updates content 

### PR DESCRIPTION
**Pull request by dakotabenjamin**
Looking for feedback on what is missing, what changes are needed. Currently, the main change needed is the Author names need to be made more name-like, but that can be done with a bulk find-replace for each name.

### CODE REVIEW

**Comment by smit1678** [comment]
@dakotabenjamin Awesome. Nice work. 

One question is urls for old blog posts. 

Right now we don't the date and we use dashes within the url: `https://dakotabenjamin.github.io/hotosm-website/updates/newly-revealed-shina-boundaries-offer-unprecedented-hyperlocal-data-for-decisionmakers/`. I like this and I think this is the way we should go forward with new blog posts. 

But the Drupal site uses underscores and puts the date within the url before the title: `https://www.hotosm.org/updates/2018-02-22_newly_revealed_shina_boundaries_offer_unprecedented_hyperlocal_data_for`. 

We could handle this with redirects, but we'd need to generate a list of those redirects. What about adding the permalink for all old blog posts to be what is generated by Drupal? Then we won't have to do redirects for old posts and then we'll have nice clean urls going forward?

**Comment by dakotabenjamin** [comment]
@smit1678 It seems that some posts are truncated at 80 characters and some (like the link you used as an example) are truncated at different lengths. Am I missing a pattern here? 

https://dakotabenjamin.github.io/hotosm-website/updates/2017-10-02_microgrants_humanitarian_mapping_of_coastal_wetlands_and_fishing_livelihoods_for
https://www.hotosm.org/updates/2017-10-02_microgrants_humanitarian_mapping_of_coastal_wetlands_and_fishing_livelihoods_for

https://www.hotosm.org/updates/2018-02-22_newly_revealed_shina_boundaries_offer_unprecedented_hyperlocal_data_for
https://dakotabenjamin.github.io/hotosm-website/updates/2018-02-22_newly_revealed_shina_boundaries_offer_unprecedented_hyperlocal_data_for_decisionmakers

EDIT: Maybe it cuts off to the nearest word?

**Comment by smit1678** [comment]
@dakotabenjamin Oh weird. I'm not sure, maybe @xamanu knows a bit more of about how Drupal is doing the url generation. 

Is this causing difficulty on the import to generate the permalinks?

**Comment by dakotabenjamin** [comment]
It will cause some dead links, but most pages are generated just fine

If I knew exactly how drupal generates links I could account for all the cases and be confident that the new links are identical. Right now I'm guess-n-checking for things like colons, commas, etc.

**Comment by smit1678** [comment]
@dakotabenjamin Ok makes sense. Think there is a lot? Maybe we could handle these as they come up? Manually fix the permalinks?

**Comment by dakotabenjamin** [comment]
IIRC there's no more than 30 pages with long titles that needed to be truncated.

**Comment by dakotabenjamin** [comment]
The authors links are now working properly in the posts. 

Last thing that doesn't need to be fixed in this pr is adding support for multiple authors. I'm comfortable merging this unless there's anything else.

**Comment by smit1678** [comment]
@dakotabenjamin great. Good from my end to merge this. @brendangatens anything else we should consider before merging?

**Comment by brendangatens** [comment]
@smit1678 nothing I can think of. Once merged, I'll make a few fixes to make sure the appropriate posts are showing up on a person's profile and get rid of repeating posts that I had put in place to expand my sample data set.

**Pull request merged**
