### PR TITLE
Update andrew-makachia.markdown

### PR DESCRIPTION
**Pull request by AndrewM014**
Fixes #[Add issue number here]

Changes: 

Screenshots of the change:

### CODE REVIEW

**Review by ramyaragupathy — COMMENTED** [review]
Hey @AndrewM014 - So your bio has to go right below the frontmatter just like how you specified in your earlier patch. https://github.com/hotosm/hotosm-website/pull/569/files

**Comment by AndrewM014** [comment]
Thanks Ramya,

I did not get any feedback on the bio hence the change. Please let me know
what i need to do, and also how to upload a picture.

Regards,
Andrew

**Comment by ramyaragupathy** [comment]
Hey @AndrewM014 - in the current doc content followed by `--` and ending with `--` is the front matter and this information is used to populate data during page load. 

To add a picture to your profile:
- Upload your image to `_uploads` folder
- Now pick the image name and add a field to your profile post's front matter 
`Photo: "/uploads/filename.jpg"`

For the bio:
- Your bio blur is part of the front matter. So you have to move the content outside.

A sample file for reference:

```
--
title: Andrew Makachia
date: 2019-06-04 13:33:00 Z
Photo: "/uploads/filename.jpg"
Member Type:
  Is Voting Member: true
--

I have a cumulative 10 years working experience, out of which 5 years have been with a UN 
agency and an International Organization. I was tasked with Information management and
Regional Coordination and Market Analysis with. Currently, my work encompasses offering 
support on information and data services, capacity building, coordination and data 
visualization.

```

**Comment by ramyaragupathy** [comment]
Moving convo to https://github.com/hotosm/hotosm-website/pull/597

**Pull request closed without merging**
