### PR TITLE
Fix empty field in project-item

### PR DESCRIPTION
**Pull request by bismitaguha**
#396 Project-items empty fields handled. Extra hyphen removed. @ramyaragupathy @smit1678  Please review this PR.
Screenshot from 2019-03-31 21-02-09

### CODE REVIEW

**Comment by Muskan284** [comment]
@codefab99 I have already sent a pr for this issue  11 days ago #484

**Comment by bismitaguha** [comment]
@Muskan284 The changes made in author.html are not needed.

**Comment by Muskan284** [comment]
@codefab99  i sent pr before the changes in author.html were merged thats why its showing changes in author.html file .

**Comment by bismitaguha** [comment]
Not showing as merged

**Comment by ramyaragupathy** [comment]
@codefab99 - Seems like @Muskan284 has already opened a PR for this. Thanks for looking into this though!

**Pull request closed without merging**
