### PR TITLE
Viz changes for project pages

### PR DESCRIPTION
**Pull request by ramyaragupathy**
### Updates so far

image

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
### Items to ship 🚢 
- [x] Add campaign tags to well-known projects for local testing
- [x] Image replaced with a map
- [x] Generate a data file with projects aggregated by campaign tag
- [x] Load TM projects with relevant campaign tag
- [x] Bring back project title as page header
- [x] Bring back program type & countries list
- [x] Zoom control for map
- [x] Update data file to include edit count for TM projects
- [x] Compute summary stats using the aggregated data file
- [x] Arrive at project status based on `duration` metadata
- [x]  Control page size using`View more` for description text
- [x] Additional metadata fields - reports, tools, OSM data
- [x] Update lambda

**Comment by ramyaragupathy** [comment]
@russdeffner @smit1678 - Could you please help fill up relevant campaign tags for the project files in this repo?

**Comment by ramyaragupathy** [comment]
@russdeffner has begun work on matching campaign tags and updating files in siteleaf.

**Comment by russdeffner** [comment]
@ramyaragupathy - after pondering a moment, I think it would be better to title this "tm_campaign" vs. "tm_projects". This will be more consistent and make way to add "tm_organization" and other tm links with matching terminology. Thoughts?

**Comment by ramyaragupathy** [comment]
Agree @russdeffner - Like discussed in the call, we might want to include org details as well. So it makes sense to have self-explaining metadata fields rather than just mentioning `tm_projects`

**Comment by ramyaragupathy** [comment]
point-polygon

- Polygon boundaries data file is not complete for all projects. Some of the project boundary fetch failed, so you might not see a polygon matching for all centroids
- Not all projects have the campign tag filled out.
- Map view is by default world view for projects across countries and restricted to country bbox when only one country in involved

**Comment by ramyaragupathy** [comment]
Close to 1095 TM projects do not have a campaign tag mentioned, we need to keep the map interaction accomodative  for the following project types:

- Projects with no TM match (could be a field mapping or a case of TM project missing the metdata information)
   - Spread across multiple countries - **world map with highlight countries with min & maz zoom at  the same level**
   - Implemented in One country - **Country highlighted with min & maz zoom at  the same level**
- Projects with TM match
  - Spread across multiple countries - **world map with highlight countries & project centroids/polygons loaded. Polygons appear after 2 zoom levels**
multiplecountries
   - Implemented in One country - **Country highlighted with project centroids/polygons loaded. Polygons appear after 2 zoom levels**
onecountry

Also proposing to move the edit circle away since it is:
- masking the country highlight
- steals away the limelight from the project count. We could have a separate edit layer and have it appear/disappear on user input

Other items to include in interaction:
- [x] Add a Legend for Centroids & polygons
- [x] Panel on top left to encourage zooming in
- [x] Hover interaction to show project details in a white box right below the legend
- [x] Show/hide project count in stats when there is no TM match
- [x] Hide centroids when polygons appear - I'm skeptical of this for now since  data aggregate from lambda fails on polygon boundar fetch randomly.  Uploads to Mapbox studio fails with out of bounds error and this error reproduction is not consistent.

**Comment by ramyaragupathy** [comment]
- Layout now alternates between map & image depending on `tm_campaigns` liquid tag.
- BBox for map view is generated from project centroids
- Legend & click interaction added for centroid layer

**Comment by ramyaragupathy** [comment]
Per convo w/ @mataharimhairi - she'll be adding METEOR project details as pilot. @ramyaragupathy & @mataharimhairi will follow up w/ @smit1678 once this integration is done.

**Comment by ramyaragupathy** [comment]
@jessbeutler - Per voice I will wait for you to update data on the following projects

- eliminar-la-malaria-2020
- botswana_field_data_collection_to_support_the_national_malaria_programme

Drive: https://drive.google.com/drive/u/1/folders/1ofRyAs4WZoftpFj8aeDkx1c4_kwdXCPR
Meteor file content: https://raw.githubusercontent.com/hotosm/hotosm-website/project-pages-viz/_projects/modelling-exposure-through-earth-observation-meteor.markdown
JSON generation: http://geojson.io

**Comment by smit1678** [comment]
@ramyaragupathy Running through a review and a couple points of feedback on the map to address: 

- [x] Cursor over map is only pointer 👆 can we adjust to a ✋ over the map and then change to 👆 for interactions like TM project points. 
- [x] Add thousands separator to the map popup 

Listing out our other next actions to finalize: 

- [x] create project folders in M&E project folder on google drive for example projects
- [x] add data to those project folders for example projects
- [x] add documentation to /docs page for creating new projects on the website with maps

anything else?

**Comment by ramyaragupathy** [comment]
All items covered in your list - heads down on a tag analysis work, will update here after this.

**Comment by ramyaragupathy** [comment]
Documentation for new metadata fields in project files: https://paper.dropbox.com/doc/Guidelines-to-add-a-new-project-file-to-website--AY3KspjuPjp5rF3OjySd0TdxAg-u3tK8ifHLOxBKZBKRISNg

**Comment by smit1678** [comment]
@ramyaragupathy Looks great! I updated the redirect links along to fix the redirect loops and then tested adding a map to a new project, Mini Grids, to review the guidelines. Let's merge this to get it live and then list out some of the next steps plus some ideas for further improvements/optimizations.

**Pull request merged**
