### PR TITLE
Update and rename 2018-06-12-a-fresh-look-for-hotosm-dot-org.markdown…

### PR DESCRIPTION
**Pull request by IknowJoseph**
… to 2018-06-13-hot-2018-annual-meeting-and-election-results.markdown

I have copied and edited the above to create a new blog post. I'm not sure that this is the correct method... Please let me know!

### CODE REVIEW

**Comment by smit1678** [comment]
@IknowJoseph Thanks! I think you accidentally deleted the hotosm-dot-org.markdown post along with adding the new file. The filenaming is correct for the new post, you're just deleting the old file. Did you cut the text from the original post?

**Comment by IknowJoseph** [comment]
Hi Nate, yes, apologies, I see that I messed this up. I was hoping to copy
the most recent entry, make changes and save as a new file, but apparently
that didn't go as I planned. Is there a web interface method on github for
creating these new files, or should I be using siteleaf for blog entries?

**Comment by smit1678** [comment]
@IknowJoseph Yeah no worries, it can be tricky sometimes. You can add and edit files directly through the web UI on github.com. It is slightly easier via Siteleaf for making blog entries so that's an option as well. We wrote some brief instructions here: https://github.com/hotosm/hotosm-website/wiki/Managing-content-via-Siteleaf

Within Github, there is a create new file button. So if you go to the `_posts` folder, you can then create a new file and copy and paste the data there. 

hotosm-website 2018-06-14 12-02-04

**Comment by IknowJoseph** [comment]
Thanks @smit1678  please close this one now that I've created a new file. I think there could be issues with that, but I know I don't want this change merged :)

**Comment by smit1678** [comment]
Sounds good @IknowJoseph, closing this out in preference for https://github.com/hotosm/hotosm-website/pull/316

**Pull request closed without merging**
