### PR TITLE
Fix/files to cdn

### PR DESCRIPTION
**Pull request by dakotabenjamin**
Fixes SiteLeaf issue with full storage. 

Changes: 
I uploaded all the files in `_uploads` to our CDN, then wrote a short shell script that examines all the files in `_uploads` and re-references them to the external CDN link. Because this process was automatized, we should take as many precautions before merging to ensure any mistakes that were made are fixed. Please don't merge until at least two or more different folks have taken a look. 

There are still some files in the _uploads folder that were not touched during the script. I take it that these are not currently being used on the site at all (perhaps uploaded but never used, or replaced by newer files, etc). I need to check, but these likely can also be removed.

### CODE REVIEW

**Review by willemarcel — APPROVED** [review]
I tested a lot of pages and it seems good

**Review by eternaltyro — APPROVED** [review]
Looks good overall. Tested several images and visually checked the changelog.

**Comment by ramyaragupathy** [comment]
Hey @dakotabenjamin - this looks great 💯 . Is it possible we could move the cdn link to a  [site variable](https://jekyllrb.com/docs/variables/#site-variables)  (setting it in [_config.yml)](https://github.com/hotosm/hotosm-website/blob/gh-pages/_config.yml) which can then be accessed with `site.` prefix across the front matter? Now I don't know whether global variables are accessible in front matter, but if we figure this out - it becomes easier for us to configure the image source option.

cc @eternaltyro @willemarcel

**Comment by willemarcel** [comment]
@ramyaragupathy I didn't understand how frontmatter works, but I think it would be an ideal solution if we could have that. I was searching for a similar solution yesterday.

**Comment by dakotabenjamin** [comment]
@ramyaragupathy I don't currently know if that is possible but I agree it would be a good idea. However I don't want to delay merging this PR since it is functional and necessary to allow publishing again.

**Pull request merged**
