### PR TITLE
Viz changes for country pages

### PR DESCRIPTION
**Pull request by ramyaragupathy**
cc @brendangatens @smit1678 @dakotabenjamin

### CODE REVIEW

**Comment by ramyaragupathy** [comment]
Here's a screenshot what I'm thinking for country map:

image
country-viz


@brendangatens @smit1678 would be great to know your inputs here.  Yet to integrate the scripts for checkboxes and please ignore the font changes.

**Comment by brendangatens** [comment]
I like where you're going with the filters. I think it will be important to add some context to them. How can we communicate that a country has no active projects—or that its tasking manager projects were all from 2014 to 2015—without requiring the user to do the job of clicking around to explore. We could only display the filters relevant to that country (so if a country has no projects form 2015, that filter wouldn't display) or we could add the number of projects next to each filter `Active Projects (0)` `Archived Projects (12)`.

Terminology-wise, how can we differentiate between tasking manager _projects_ (shown on the map) and the larger portfolio _projects_ that are listed down the page? The _Filter projects_ and _Uganda has 3 projects_ labels in the sidebar are referring to different things.

Even if we do find a unique names for each type of project, we'll need to make clear what the labels in the sidebar are referring to. Seeing "Uganda has 3 projects" next to a map that has 50 or so markers is confusing. Maybe we should find a new place for the sidebar items that don't directly correspond to something on the map.

**Comment by ramyaragupathy** [comment]
@brendangatens - At least for year I'm thinking in the same line - listing only those years in which there was a tasking manager project created. Like the idea of having numbers for active & archived projects. We could display just an `Active(0)` label without checkbox in case there are no active projects in a country.
Agree with your point on the terminology used.  As we include filters, it is necessary to keep the language right to communicate the project context right.  I noticed this initially, but still haven't thought through on what could be the right word here.

@smit1678 - I've made a modification to the lambda to include created data for each projects. Project creation date comes from a separate endpoint. It is not part of the main project link. So this change was required for the data generation. While there're no hurdles in implementing this, I'm unable to get this lambda run successfully owing to data fetch failures from TM. I've been trying to get a successful run today, but data fetch fails repeatedly. Once this is done - I'll update the script for the filter checkboxes. This is not a blocker at the moment though.

Ramya's next actions:
- [ ] Get the modified data file from a successful lambda run
- [ ] Include checkbox script for filtering to function

**Comment by ramyaragupathy** [comment]
Update on lambda: I was able to get it past the Tasking Manager error today. Including project summary api for creation date, results in memory error.  Restructuring the code flow to get this done.

**Comment by ramyaragupathy** [comment]
Including project summary results in memory usage peaking at 3.5GB well beyond the current 3GB memory limit of lambda functions. This is because the json  data for close to 4K projects are stored in process memory.

There are 3 solutions that I could think right now:
1. Modify the project API end point to return created date. https://github.com/hotosm/tasking-manager/issues/1162

2. Retain the current code flow , but move the function out of to an EC2 instead of a lambda. W'd need an docker and cloud formation,  that runs our code in an isolated container.
3. Restructure the code flow - 
current flow: fetch project list ->  iterate over the list to get project area, changeset comments  -> fetch edit counts using changeset comments -> push to S3 and Github
modify this to: fetch project list -> iterate over the list to get project summary -> fetch area -> fetch edit counts   -> push to S3 and Github

Though solution#1 is the best, till it is taken up for review, I'd like to have to solution#3 working in a separate branch within stats-collector.

**Comment by ramyaragupathy** [comment]
@brendangatens - any pointers on why the `country-map-wrap` doesn't load to the full height initially? The div fills in on window resize though. I tried setting a delay for the map to load after contact details and filters load in the contact div. That doesn't help though.

extra-div

**Comment by smit1678** [comment]
@ramyaragupathy 👍 It's looking good. To recap a couple things, let's get some feedback on the title placement (since we're using the older centroid as a workaround of the map sizing issue) and the experience of filtering and browsing. 

I will merge and then you can follow up with some tickets that outline some of these items.

**Comment by ramyaragupathy** [comment]
Thanks for the review @smit1678! Just noticed the impact-filter jquery fix, that went in with this PR works fine.

**Pull request merged**
